### ISSUE TITLE
Error on open app in Xcode Simulator & Failure to download...

### ISSUE THREAD

**Issue by jhuckstead** [theniceboy/HoldToSaveImage#2]
Hello,

Great job here, I love it.  I am having some trouble however... When I load your project in Xcode and just run it with no changes, I get an error as soon as the app opens in the simulator.

The error message in console: 

HoldToSaveImage[52488:4189544] Operation <DDWebKitOperation: 0x6000000fe180>: container <WebFrame: 0x60800001b870> has been modified too many times, aborting

However the app does open and the webview appears to work fine.  The longpress action fires off and I see the download or cancel buttons... but when I press save, the "saving" dialog appears at the top, but then goes away after a few seconds and nothing is downloaded.

The popup dialog asking for permission, that I noticed in your demo, does not appear either.

I can't be sure that the error code and failure to download are related.  I have done some searching on that error message and I get nowhere.

Any help would be appreciated... I launched my Android app 3 months ago, and am just struggling through this Xcode BS, and all of the iOS webkit limitations.

**Comment by theniceboy** [comment]
Hi,

This code was written a long time ago. I'm sorry for the delay.

The problem was that I accidentally deleted the line "UIImageWriteToSavedPhotosAlbum(saveableImage!, self, #selector(self.image(_:didFinishSavingWithError:contextInfo:)), nil)"

I'm sorry for the inconvenience, and I'm very happy to know that you see my code useful. I updated the code, please also see the "Usage" section in the new README. The privacy settings in iOS 10 have changed that you have to change your app's plist file.

**Comment by theniceboy** [comment]
Please tell me if anything still goes wrong. If it works then I will close the issue.

**Comment by jhuckstead** [comment]
Worked like a charm!!! Thank you for the fast reply.  You have saved my app, and saved me dozens of frustrating hours!

**Comment by theniceboy** [comment]
No problem
Have a good day!
